# Generated by Django 3.2.5 on 2022-02-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
